---
- name: Check for online hosts
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Ping for reachability
      command: ping -c3 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true

    - name: Group hosts by online
      group_by: key=reachable
      when: ping_result.rc == 0

- name: Set default cisco configuration items
  hosts: reachable
  gather_facts: False
  connection: network_cli

  tasks:
    - include_role:
        name: cisco_defaults
      vars:
        ansible_network_os: ios