---
# tasks file that sets ntp settings
  - name: Clear NTP settings
    cisco.ios.ios_ntp:
      state: absent
    notify: save ios

  - name: Set NTP Server
    cisco.ios.ios_ntp:
      server: "{{ item }}"
      source_int: "{{ ntp_source_interface }}"
      state: present
    with_items: "{{ ntp_server }}"
    notify: save ios